import React, { useRef } from 'react';
import { NewspaperData } from '../types';
import { Button } from './Button';
import { Download, X } from 'lucide-react';

type NewspaperOverlayProps = {
  data: NewspaperData;
  onClose: () => void;
};

export const NewspaperOverlay: React.FC<NewspaperOverlayProps> = ({ data, onClose }) => {
  const contentRef = useRef<HTMLDivElement>(null);

  const handleDownload = () => {
    // Create a standalone HTML file
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>${data.title} - ${data.issueNumber}</title>
        <style>
          body { font-family: 'Times New Roman', serif; background: #fdf6e3; color: #2c2925; padding: 40px; margin: 0; }
          .container { max-width: 800px; margin: 0 auto; border: 1px solid #444; padding: 20px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); background: #fdf6e3; }
          .header { text-align: center; border-bottom: 2px double #444; padding-bottom: 10px; margin-bottom: 20px; }
          .title { font-size: 48px; font-weight: bold; text-transform: uppercase; letter-spacing: 2px; line-height: 1; margin-bottom: 10px; }
          .meta { display: flex; justify-content: space-between; border-top: 1px solid #444; border-bottom: 1px solid #444; padding: 5px 0; margin-top: 10px; font-style: italic; font-size: 14px; }
          .lead-story { margin-bottom: 30px; }
          .headline { font-size: 32px; font-weight: bold; line-height: 1.1; margin-bottom: 10px; }
          .subhead { font-size: 18px; font-style: italic; margin-bottom: 15px; color: #555; }
          .content { font-size: 16px; line-height: 1.6; text-align: justify; column-count: 2; column-gap: 30px; }
          .side-stories { display: grid; grid-template-columns: 1fr 1fr; gap: 30px; border-top: 1px solid #aaa; padding-top: 20px; margin-top: 20px; }
          .side-story h3 { font-size: 20px; margin-top: 0; margin-bottom: 8px; font-weight: bold; }
          .side-story p { font-size: 15px; line-height: 1.5; margin: 0; text-align: justify; }
          .briefs { background: #eee8d5; padding: 15px; margin-top: 20px; border: 1px solid #d4c4a8; }
          .briefs h4 { margin-top: 0; text-transform: uppercase; font-size: 14px; border-bottom: 1px solid #aaa; padding-bottom: 5px; margin-bottom: 10px; }
          .briefs ul { margin: 0; padding-left: 20px; }
          .briefs li { margin-bottom: 5px; font-size: 14px; }
          .rumors { margin-top: 20px; font-style: italic; color: #666; font-size: 14px; border-top: 1px solid #ddd; padding-top: 10px; }
          @media print {
            body { padding: 0; background: white; }
            .container { border: none; box-shadow: none; width: 100%; max-width: none; }
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <div class="title">${data.title}</div>
            <div class="meta">
              <span>${data.issueNumber}</span>
              <span>${data.date}</span>
              <span>Price: 1 Denar</span>
            </div>
          </div>
          
          <div class="lead-story">
            <div class="headline">${data.leadStory.headline}</div>
            <div class="subhead">${data.leadStory.subhead}</div>
            <div class="content">
              ${data.leadStory.content.split('\n').map(p => `<p style="margin-top: 0; margin-bottom: 1em;">${p}</p>`).join('')}
            </div>
          </div>

          <div class="side-stories">
            ${data.sideStories.map(s => `
              <div class="side-story">
                <h3>${s.headline}</h3>
                <p>${s.content}</p>
              </div>
            `).join('')}
          </div>

          <div class="briefs">
            <h4>News Briefs</h4>
            <ul>
              ${data.briefs.map(b => `<li>${b}</li>`).join('')}
            </ul>
          </div>

          <div class="rumors">
            <strong>Rumor Mill:</strong> ${data.rumors.join(' ')}
          </div>
          
          <div style="text-align: center; margin-top: 30px; font-size: 12px; color: #888;">
            Generated by Calradia Chronicles AI Press
          </div>
        </div>
      </body>
      </html>
    `;

    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${data.title.replace(/\s+/g, '_')}_${data.date}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4 overflow-y-auto">
      <div className="bg-[#fdf6e3] text-[#2c2925] max-w-4xl w-full shadow-2xl rounded-sm overflow-hidden flex flex-col max-h-[90vh]">
        {/* Toolbar */}
        <div className="bg-stone-800 p-2 flex justify-between items-center shrink-0">
          <div className="text-stone-400 text-sm">Newspaper Preview</div>
          <div className="flex gap-2">
            <Button variant="primary" onClick={handleDownload} className="flex items-center gap-1">
              <Download size={16} /> 下载 .html
            </Button>
            <Button variant="secondary" onClick={onClose} className="flex items-center gap-1">
              <X size={16} /> 关闭
            </Button>
          </div>
        </div>

        {/* Paper Content */}
        <div className="p-8 overflow-y-auto font-serif" ref={contentRef}>
          <div className="border-b-4 border-double border-stone-800 pb-4 mb-6 text-center">
            <h1 className="text-6xl font-black uppercase tracking-wider mb-2 leading-none">{data.title}</h1>
            <div className="flex justify-between border-y border-stone-800 py-1 text-sm italic font-medium">
              <span>{data.issueNumber}</span>
              <span>{data.date}</span>
              <span>Price: 1 Denar</span>
            </div>
          </div>

          <div className="mb-8">
            <h2 className="text-4xl font-bold leading-tight mb-2">{data.leadStory.headline}</h2>
            <h3 className="text-xl italic text-stone-600 mb-4">{data.leadStory.subhead}</h3>
            <div className="text-lg leading-relaxed text-justify columns-1 md:columns-2 gap-8 whitespace-pre-wrap">
              {data.leadStory.content}
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 pt-6 border-t border-stone-400">
            {data.sideStories.map((story, idx) => (
              <div key={idx}>
                <h4 className="text-xl font-bold mb-2">{story.headline}</h4>
                <p className="text-base leading-relaxed text-justify">{story.content}</p>
              </div>
            ))}
          </div>

          <div className="mt-8 bg-[#eee8d5] p-4 border border-[#d4c4a8]">
            <h5 className="text-sm font-bold uppercase border-b border-stone-400 pb-1 mb-2">News Briefs</h5>
            <ul className="list-disc list-inside space-y-1 text-sm">
              {data.briefs.map((brief, idx) => (
                <li key={idx}>{brief}</li>
              ))}
            </ul>
          </div>
          
          <div className="mt-4 text-sm italic text-stone-600">
            <span className="font-bold not-italic">Rumor Mill: </span>
            {data.rumors.join(' ')}
          </div>
        </div>
      </div>
    </div>
  );
};
